OsmosysSoftware/osmo-x

CONTRIBUTING.md

This commit adds the CONTRIBUTING.md file to provide guidelines for contributing to the project. The document outlines the process for reporting issues, submitting pull requests, setting up a development environment, and following coding and commit guidelines.
This contribution guide aims to make it easier for community members to understand how they can contribute effectively to the project. By following these guidelines, we can work together to improve and enhance the project for everyone.
Closes #1

docs: add CONTRIBUTING.md for project contribution guidelines

---

package.json

Adjusted the repository description for better clarity and updated the author field in package.json with accurate information.

docs: update repository description and author field

---

.env.example
.gitignore
package-lock.json
package.json
src/app.module.ts
src/config/database/configuration.ts

This PR introduces a new feature to add TypeORM configurations for the ability to connect to a database.
The configuration values to be used while connecting to the DB are specified through `.env` file, which can be created based on the `.env.example` file.

feat: configure TypeORM to connect to Database

---

.env.example
.vscode/settings.json
package-lock.json
package.json
src/common/constants/database.ts
src/common/constants/notifications.ts
src/config/typeorm/configuration.ts
src/database/migrations/1692870736644-migration.ts
src/main.ts
src/models/notifications/entities/notification.entity.ts

- Updated the entity and migration files for the Notification model.
- Added class-validator decorators to the entity file.

feat: update entity and migration

---

README.md

Added an initial README file containing basic information about the project, its purpose, and setup instructions.

docs: add initial readme with basic project information

---

LICENSE
README.md

docs: add LICENSE

---

README.md

Add contributors section  in readme

docs: add contributors section in readme

---

src/jobs/consumers/notifications/smtp-notifications.job.consumer.ts

Removed unintentionally added code.

refactor: revert unintentional code

---

CODE_OF_CONDUCT.md
src/common/types/NotificationData.ts
src/database/migrations/1692870736644-migration.ts
src/jobs/consumers/notifications/smtp-notifications.job.consumer.ts
src/models/notifications/dtos/create-notification.dto.ts
src/models/notifications/entities/notification.entity.ts
src/models/notifications/notifications.controller.ts
src/models/notifications/notifications.service.ts

- Added validator and creating API using separate DTO
- Refactored all related code accordingly
- Updated result value to return to object
- Fixed migration default value

refactor: improve notifications create API

---

package-lock.json
package.json
src/config/logger.config.ts
src/main.ts

- Added winston to be used with nestJS logger
- Have added daily rotate log
**Example Logs in file**
`error-2023-09-01.log`
```json
{"timestamp":"2023-09-01T05:32:39.330Z","level":"error","message":"{\n  \"message\": \"Testing Error\",\n  \"stack\": \"Error: Testing Error\\n    at bootstrap (/home/vikas/work/projects/osmo-notify/src/main.ts:25:11)\\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\"\n}","stackTrace":[null]}
```
`combined-2023-09-01.log`
```json
{"timestamp":"2023-09-01T05:32:39.304Z","level":"info","message":"NotificationsController {/notifications}:"}
{"timestamp":"2023-09-01T05:32:39.304Z","level":"info","message":"Mapped {/notifications, POST} route"}
{"timestamp":"2023-09-01T05:32:39.324Z","level":"info","message":"Nest application …
```

feat: add logger to project

---

src/jobs/consumers/notifications/smtp-notifications.job.consumer.ts
src/models/notifications/notifications.service.ts

This PR adds logs for different actions and errors that may occur when creating, queuing or sending notifications.
- Add logging messages for getting and adding pending notifications to queue, sending them
- Add logging message for creating notification
- Add logging error messages on failure to add notification to queue or sending
Sample console logs output
```
[OsmoNotify] Info       9/1/2023, 2:20:00 PM [NotificationsService] Starting CRON job to add pending notifications to queue +11s
[OsmoNotify] Info       9/1/2023, 2:20:00 PM [NotificationsService] Getting all active pending notifications +1ms
[OsmoNotify] Info       9/1/2023, 2:20:00 PM [NotificationsService] Adding 0 pending notifications to queue +11ms
[OsmoNotify] Info       9/1/2023, 2:20:02 PM …
```

feat: add logs for actions and errors

---

docs/development-setup.md

This PR fixes the command for running migrations as mentioned in the development setup doc.

docs: fix run migration command

---

.env.example
package-lock.json
package.json
src/app.module.ts
src/common/constants/notifications.ts
src/jobs/consumers/notifications/wa360dialog-notifications.job.consumer.ts
src/jobs/producers/notifications/notifications.job.producer.ts
src/modules/notifications/dtos/create-notification.dto.ts
src/modules/notifications/entities/notification.entity.ts
src/modules/notifications/notifications.module.ts
src/modules/notifications/notifications.service.ts
src/modules/notifications/queues/wa360dialog.queue.ts
src/services/whatsapp/wa360dialog/wa360dialog.service.spec.ts
src/services/whatsapp/wa360dialog/wa360dialog.service.ts

This PR adds and implements the 360dialog service functionality for sending whatsapp messages.
Sample request body:
```json
{
"channelType": 3,
"data": {
"to": "919004812051",
"type": "template",
"template": {
"namespace": "d8bcb6bd_2ab2_439c_9d9e_947501266c77",
"name": "ir_incident_resolution",
"language": {
"policy": "deterministic",
"code": "en"
},
"components": [
{
"type": "body",
"parameters": [
{
"type": "text",
"text": "Bishal Biswas"
},
{
"type": "text",
"text": "WNK227"
},
{
"type": "text",
"text": "Massive Earthquake"
},
{
"type": "text",
"text": "Power Grid"
},
{
"type": "text",
"text": "Bishal Mondal"
},
{
"type": "text",
"text": "Vikas"
},
{
"type": "text",
"text": "Open"
},
{
"type": "text",
"text": "10"
},
{
"type": "text",
"text": "15755"
}
]
}
]
}
}
}
```
Sample response: …

feat: add 360dialog service for sending whatsapp notification

---

docs/add-new-provider.md

Updated steps to add new provider based on new modular structure.

docs: update add new provider

---

.github/workflows/main.yml
CONTRIBUTING.md
docs/development-setup.md
docs/production-setup.md
package-lock.json
package.json

- upgraded node version to 20
- updated github action for lint/build to use node 20
- updated documents

feat: upgrade node 18 to node 20

---

src/modules/notifications/notifications.service.ts

1. We will be running cron **EVERY_1_SECONDS** in order to push notifications faster in queue instead of waiting for 1 minute in worst case. If its already processing we skip that cron.

feat: send notification immediately when api is called

---

src/modules/notifications/notifications.module.ts
src/modules/notifications/notifications.service.ts
src/modules/notifications/schedule/schedule.service.spec.ts
src/modules/notifications/schedule/schedule.service.ts

- moved cron definition to schedule service which is part of notification module.

refactor: add schedule service to define cron

---

apps/api/package-lock.json
apps/api/package.json
apps/portal/package-lock.json
apps/portal/package.json

- Major version update for portal to 1.0.0.
- Minor version update for backend to 1.1.0

chore: bump backend to v1.1.0 and frontend to v1.0.0

---

apps/api/package-lock.json
apps/api/package.json
apps/portal/package-lock.json
apps/portal/package.json

chore: bump version to 2.0.0

---

apps/api/OsmoX.postman_collection.json

---
- Update postman collection
- Add new requests that were missing from the collection
- Add/update scripts for testing API Response
NA
NA
**Query request and response:**
NA
**Documentation changes:**
NA
**Test suite output:**
NA
NA
**Additional notes:**
NA

docs: add scripts to postman collection

---

apps/api/OsmoX-API.postman_collection.json
apps/api/OsmoX.postman_collection.json
apps/api/docs/channels/sms-Twilio.md
apps/api/docs/channels/vc-twilio.md
apps/api/docs/usage-guide.md

_Note: Reviewer should ensure that the checklist and description have been populated and followed correctly, and the PR should be merged only after resolving all conversations and verifying that CI checks pass._
---
Add usage guide for Twilio Voice Call
NA
Test results
**Query request and response:**
NA
**Documentation changes:**
NA
**Test suite/unit testing output:**
NA
NA
**Additional notes:**
NA

docs: add usage guide for twilio voice call

---

apps/api/src/config/logger.config.ts

_Note: Reviewer should ensure that the checklist and description have been populated and followed correctly, and the PR should be merged only after resolving all conversations and verifying that CI checks pass._
---
Update logger to get application name from package.json
Remove the hardcoded app name
NA
Local: Uses lowercase `osmox` as written in `package.json`
Docker:
**Query request and response:**
NA
**Documentation changes:**
NA
**Test suite/unit testing output:**
NA
NA
**Additional notes:**
NA

feat: update logger to get application name from package.json

---

apps/api/package-lock.json

Osmosys Developers must include the Pinestem task link in the PR.
[OSXT-369](https://pinestem.com/dashboard.html#/tasks/OSXT-369/details/?companyId=453&isPrevNext=1)
_Note: Reviewer should ensure that the checklist and description have been populated and followed correctly, and the PR should be merged only after resolving all conversations and verifying that CI checks pass._
---
Update API dependencies
For dependency updates, I think it would be better that we handle moving to nestjs 11 in a separate PR and task
There seems to be some npm issues with nestjs cli, causing "low" vulnerabilities in node modules
So checking the migration guide: …

build: update api dependencies
