OsmosysSoftware/osmo-x

.env.example
src/config/database/configuration.ts

This PR updates the datatabase TypeORM configuration to get the database type value from `.env` file instead of being hardcoded.
Other related changes:
- Update `.env.example` to add `DB_TYPE`
- Use `getOrThrow` instead of `get` in `configService`
Fixes #5

fix: fetch typeorm database type value from .env

---

package.json
src/config/typeorm/configuration.ts
src/database/migrations/1692870736644-migration.ts
src/models/notifications/entities/notification.entity.ts

This PR adds the migrations functionality for database changes through TypeORM.
- `notification.entity.ts` file has been created to map values to database.
- `typeorm/configuration.ts` exports the required DataSource to be used when running migrations commands
- `package.json` to configure the different typeorm scripts

feat: add database migrations to create notifications table

---

src/common/constants/notifications.ts
src/database/migrations/1692870736644-migration.ts
src/models/notifications/entities/notification.entity.ts

This PR makes some database related changes and improvements.
- Add constants/notifications.ts file for DeliveryStatus, tinyint for delivery_status
- Update notifications.entity file to use created constant values
- Update migration file to use tinyint for delivery_status

fix: use tinyint for delivery_status

---

.eslintrc.js

1. `'@typescript-eslint/explicit-function-return-type': ['error', { allowExpressions: true }]`: Enforces explicit return types for functions in TypeScript, allowing expression-style functions to omit return type annotations.
2. `'@typescript-eslint/no-explicit-any': 'error'`: Flags usages of **any** type in TypeScript as errors.
3. `'@typescript-eslint/no-unused-vars': 'error'`: Reports unused variables in TypeScript as errors.
4. `'no-console': 'warn'`: Generates warnings for the use of console statements.
5. `'padding-line-between-statements': [...]`: Enforces blank lines between specific statement types (e.g., functions, if statements, loops) to enhance code readability.

feat: add ESLint rules for code quality improvement

---

package-lock.json
package.json
src/common/types/NotificationData.ts
src/jobs/consumers/notifications/notifications.job.consumer.ts
src/jobs/consumers/notifications/smtp-notifications.job.consumer.ts
src/jobs/producers/notifications/notifications.job.producer.ts
src/main.ts
src/models/notifications/notifications.controller.ts
src/models/notifications/notifications.module.ts
src/models/notifications/notifications.service.ts
test/app.e2e-spec.ts

This PR implements the functionality of queues for processing notifications. Currently, only notification queue is added (for email), but new queues can be created for different channels (such as SMS, chat, etc).
- Add bull package for queue system
- Add notifications producers and consumers for adding jobs to and processing jobs in queue respectively
- Update notifications service to also add notification to queue during creation
- Update notifications module to import bull, queue services; register queue

feat: implement queue for processing notifications

---

.github/workflows/main.yml

This PR adds a GitHub Actions workflow for linting and building the Nest.js app.
- **Name**: Standard Nest.js App Flow
- **Trigger**: Pull requests to the `main` branch
- **Runs on**: Ubuntu Latest
- **Steps**:
1. Checkout code
2. Set up Node.js (v18)
3. Install dependencies
4. Lint code with `npm run lint`
- **Needs**: Lint Job (success)
- **Runs on**: Ubuntu Latest
- **Steps**:
1. Checkout code
2. Set up Node.js (v18)
3. Install dependencies
4. Build Nest.js app using `npm run build`
- Added GitHub Actions workflow for linting and building.
- Defined separate "lint" and "build" jobs with specific steps and dependencies.
- "Build" job depends on successful "lint" job completion.

feat: add GitHub actions for linting & building

---

package-lock.json
package.json
src/app.module.ts
src/jobs/consumers/notifications/smtp-notifications.job.consumer.ts
src/jobs/producers/notifications/notifications.job.producer.ts
src/models/notifications/notifications.service.ts

This PR implements the functionality of CRON to add pending notifications as fetched from database to notifications queue, scheduled to run every minute.
- Add @nestjs/schedule package, import ScheduleModule in app.module
- Add getPendingNotifications to get all notifications in pending status from database
- Add addNotificationQueue function with Cron() decorator to run every 1 minute, update status to IN_PROGRESS and add pending notifications to queue 
- Add and set isProcessingQueue flag for when cron is running

feat: add cron to process notifications queue

---

src/database/migrations/1692870736644-migration.ts
src/models/notifications/entities/notification.entity.ts

Modified the codebase to prefix all database references with 'notifi_' to maintain a consistent naming convention.

refactor: add 'notifi_' prefix to all table names

---

README.md
docs/production-setup.md
ecosystem.config.js

- Create a new `production-setup.md` file to provide comprehensive instructions for setting up the project in a production environment.
- Add a `ecosystem.config.js` file to be used by pm2.

docs: add production setup instructions

---

src/models/notifications/notifications.service.ts

This PR updates the `getPendingNotifications()` to fetch only notifications that are in `status` `1` (active), along with the `delivery_status check` of `1` (pending).

fix: fetch only active pending notifications

---

src/database/migrations/1692870736644-migration.ts

This PR updates the json data type columns `data` and `result` to text type to allow migrations to run with MariaDB versions 10.x or higher.

fix: change json columns to text type

---

.env.example
package-lock.json
package.json
src/app.module.ts
src/common/constants/notifications.ts
src/jobs/consumers/notifications/mailgun-notifications.job.consumer.ts
src/jobs/producers/notifications/notifications.job.producer.ts
src/modules/notifications/notifications.module.ts
src/modules/notifications/queues/mailgun.queue.ts
src/services/email/mailgun/mailgun.service.spec.ts
src/services/email/mailgun/mailgun.service.ts

This PR adds and implements the mailgun service functionality for sending emails. Required code changes, updates and additions have been made.
- Add mailgun.js npm package
- Update .env.example to store mailgun related env variables Update notifications constant file to add MAILGUN type Add mailgun service files for sending mail
- Add mailgun queue file to store its config
- Add mailgun consumer for processing its queue
- Update notifications producer to add notifications to correct queue based on channelType Update notifications module to register queue, add mailgun providers
Sample request body:
```json
{
"channelType": 2,
"data": {
"from": "sender@email.com",
"to": "recepient1@email.com, recepient2@email.com",
"subject": "Test subject",
"text": "This is a test …
```

feat: add mailgun service for sending mails

---

docs/channels/mailgun.md
docs/development-setup.md
docs/production-setup.md
docs/usage-guide.md

This PR adds the usage documentation guide for Mailgun channel type.
- Update development and production setup docs with new env file config
- Update main usage-guide doc to add link to mailgun doc link

docs: add mailgun channel usage guide

---

src/config/typeorm/configuration.ts

This PR updates the TypeORM DataSource configuration to specify migrations table name to be `notify_migrations` instead of default `migrations`.

fix: change migrations table name to notify_migrations

---

src/database/migrations/1692870736644-migration.ts

This PR updates the query in migration file when running revert migration to use correct table name `notify_notifications` instead of `notifications`.

fix: table name to notify_notifications for revert migration

---

src/modules/notifications/dtos/create-notification-data.dto.ts
src/modules/notifications/dtos/create-notification.dto.ts
src/modules/notifications/entities/notification.entity.ts
src/modules/notifications/notifications.service.ts

This PR adds validation to the notification data, when sent via API call and also before adding the notification ID into queue.
- Create a DTO for notification data, add rules
- Update notification dto, entity to change type of data to CreateNotificationDataDto Update notification service to validate notification data from database via the new DTO before adding to queue
Sample Erroneous Request:
```json
{
"channelType": 1,
"data": {
"to": "receiver@email.com",
"subject": "Test Notification",
"text": "This is a test notification",
"html": "<b>This is a test notification</b>"
}
}
```
Sample Response:
```json
{
"message": [
"data.from should not be empty"
],
"error": "Bad Request",
"statusCode": 400
}
```
Error Logging in Console:
```bash
[OsmoNotify] Error      9/7/2023, …
```

feat: add validation for notification data

---

src/common/http-exception.filter.ts
src/common/jsend-formatter.ts
src/modules/notifications/notifications.controller.ts
src/modules/notifications/notifications.module.ts

This PR fixes the responses sent to follow jsend formatting when making API call to create a notification.
- Add a JsendFormatter class to declare methods for formatting messages for success, fail, error
- Add an exception filter for formatting response for failed dto validations
- Update controller to add try catch block for success and error jsend response, log error when creating notification
Sample response for successful notification creation:
```json
{
"status": "success",
"data": {
"notification": {
"channelType": 1,
"data": {
"from": "sender@email.com",
"to": "receiver@email.com",
"subject": "Test Notification",
"text": "This is a test notification",
"html": "<b>This is a test notification</b>"
},
"createdBy": "LocalDev",
"updatedBy": "LocalDev",
"result": null, …
```

fix: api response to follow jsend format

---

docs/channels/mailgun.md
docs/channels/smtp.md
docs/usage-guide.md

This PR updates some outdated API responses and fixes their formatting (for comments). 
- Update sample API response in `usage-guide.md` as per jsend format (see #43)
- Fix comments in smtp and mailgun docs
- Other minor formatting and content fixes

docs: update api response formats, content fixes

---

src/common/constants/notifications.ts
src/modules/notifications/notifications.controller.ts
src/modules/notifications/notifications.service.ts

- filter out disbaled channels when adding to queue.
- throw error when channel is not enabled before creating notification.
Sample Response
```json
{
"status": "fail",
"data": "Channel 2 is not enabled"
}
```

feat: add check for enabled channels

---

osmo-notify.postman_collection.json
src/modules/notifications/dtos/providers/wa360Dialog-data.dto.ts

Added postman collection for APIs.
Added different test cases for every channel.
1. `postman` test generator and collection runner.
2. newman cli tool.
1. Install newman cli
```sh
npm install -g newman
```
(Optional for html reports)
```
npm i -g newman-reporter-html
```
2. export environment file from postman
3. Run the following command to run tests
```sh
newman run osmo-notify.postman_collection.json -e Test.postman_environment.json -r html
```
`-r html` creates a html report.

docs: add postman collection

---

src/common/jsend-formatter.ts
src/modules/notifications/notifications.controller.ts
src/modules/notifications/notifications.service.ts

This pull request introduces a new API endpoint allowing the retrieval of a notification using a single ID. The endpoint provides detailed information about the specified notification, or returns an error message if the notification is not found.
```bash
curl --location 'localhost:3000/notifications/58' \
--header 'Authorization: Bearer osmo-notify-test-key'
```
```json
{
"status": "success",
"data": {
"notification": {
"id": 58,
"channelType": 1,
"data": {
"from": "vikaskyatannawar@gmail.com",
"to": "vikas.k@osmosys.co",
"subject": "Test subject",
"text": "This is a test notification",
"html": "<b>This is a test notification</b>"
},
"deliveryStatus": 4,
"result": {
"result": {
"code": "EMESSAGE",
"response": "554 5.2.0 STOREDRV.Submission.Exception:OutboundSpamException; Failed to …
```

feat: add api to get notifications by ids

---

apps/api/.env.example
apps/api/.gitignore
apps/api/package-lock.json
apps/api/package.json
apps/api/src/app.module.ts
apps/api/src/common/guards/api-key/api-key.guard.ts
apps/api/src/common/http-exception.filter.ts
apps/api/src/modules/notifications/entities/notification.entity.ts
apps/api/src/modules/notifications/notifications.module.ts
apps/api/src/modules/notifications/notifications.resolver.spec.ts
apps/api/src/modules/notifications/notifications.resolver.ts
apps/api/src/modules/notifications/notifications.service.ts

**Description**:
This PR adds graphql and to fetch all the notifications
Implement graphql for application root
Add a function to fetch all the notifications
Add Notification Resolver
Register Returning Models by modifying notification entity.
**Curl:** 
```curl
curl 'http://localhost:3000/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:3000' -H 'Authorization: Bearer <SERVER_AUTH_TOKEN>' --data-binary '{"query":"query {\n  notifications {\n    channelType\n    createdBy\n    createdOn\n    data\n    deliveryStatus\n    id\n    result\n    status\n    updatedBy\n  }\n}"}' --compressed
```
**Sample Response:**
```
{
"data": { …
```

feat: add GraphQL to fetch notifications

---

apps/portal/src/app/views/notifications/notifications.component.html
apps/portal/src/app/views/notifications/notifications.component.scss
apps/portal/src/app/views/notifications/notifications.component.ts

This PR adds display string mappings for showing easily readable strings for Channel Type and Delivery Status in the portal instead of numeric values.
- Add deliveryStatusMap and channelTypeMap for mapping display strings for corresponding values
- Update notifications.component html to use these maps when displaying delivery status and channel type values, along with proper styles

feat: add display mappings for delivery status and channel type

---

apps/portal/package-lock.json
apps/portal/package.json
apps/portal/src/app/app-routing.module.ts
apps/portal/src/app/app.component.html
apps/portal/src/app/app.module.ts
apps/portal/src/app/auth/auth.guard.spec.ts
apps/portal/src/app/auth/auth.guard.ts
apps/portal/src/app/auth/auth.interface.ts
apps/portal/src/app/auth/auth.service.spec.ts
apps/portal/src/app/auth/auth.service.ts
apps/portal/src/app/auth/login/login.component.html
apps/portal/src/app/auth/login/login.component.spec.ts
apps/portal/src/app/auth/login/login.component.ts
apps/portal/src/app/graphql/graphql.queries.ts
apps/portal/src/app/graphql/graphql.service.ts
apps/portal/src/app/primeng.module.ts
apps/portal/src/styles.scss

This PR adds a login page for allowing admin users to login in and access the notifications page. Required guards have also been added and the token fetched on logging in is used for fetching the notifications further on.
- Create a new login component, add the required logic in login.component ts file for methods and making required method calls for logging in, creating error toasts
- Add the required html code and styles for creating a login form with basic validations on username and password, showing any login errors that occur
- Create a new auth.guard ts file for checking is user is logged in before accessing notifications page, redirect accordingly
- Add an auth.interface file for specifying the LoginRequestBody and ErrorResponse
- Create an …

feat: add login page with auth guard

---

apps/api/docker-compose.yml
apps/portal/docker-compose.yml

This PR updates the `docker-compose.yml` file for `apps/api` to add `127.0.0.1` before port bindings for server, mariadb docker and redis docker ports.

chore: add 127.0.0.1 to api docker-compose ports

---

apps/api/osmo-notify.postman_collection.json

This PR adds new requests regarding authentication and fetching notifications using graphql queries to the Postman collections. Test cases have also been added
- Add new requests for login authentication, with success and failure with invalid credentials, missing password, bad request cases with test cases
- Add new requests for fetching all notifications, with success and bad request cases with test cases
**Sample test run output:**

chore: add auth and notifications graphql requests to collection

---

apps/api/src/common/constants/notifications.ts

---
Add retry function for kaps provider 
update notification.ts file , added kaps configuration
In case of connection error Which is the first case it retry for 3 times then set the status as failed : delivery_status 6
If everything is fine it mark it as success : delivery_status 5
**Query request and response:**
N/A
**Documentation changes:**
N/A
**Test suite output:**
N/A
N/A
**Additional notes:**
N/A

feat: add retry for kaps system
